# -*- coding: utf-8 -*-
"""execution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MbDdXGjF7c0X_Aj99G49b8JequVgWhpB
"""

import keras
from keras.callbacks import ModelCheckpoint
from keras.optimizers import Adam

from matplotlib import pyplot

def study(train_ds,valid_ds,model):
  batch_size=128
  epochs=15

  checkpointer=ModelCheckpoint(filepath='model.100epochs.hdf5', verbose=1,
                              save_best_only=True)
  optimizer=keras.optimizers.Adam(lr=0.0001,decay=1e-6)

  model.compile(loss='categorical_crossentropy',optimizer=optimizer,
                metrics=['accuracy'])
  history = model.fit(train_ds,
                      batch_size=batch_size,
                      epochs=epochs,
                      verbose=2,
                      validation_data=valid_ds, # 검증 데이터
                      callbacks=[checkpointer])

  pyplot.plot(history.history['accuracy'],label='Train data')
  pyplot.plot(history.history['val_accuracy'],label='Valid data')
  pyplot.legend()
  pyplot.show()

  return model