# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oa8qwsM6y-t7bKqBot8-1WIXZw7Nlk8J
"""

!pip install import_ipynb
import import_ipynb



from pre_ready import PreProcessing
from model import build_model
from execution import study
from evaluation import evaluate
from Input import image_input
from output import image_output

data_preprocessor = PreProcessing(
    image_height=135,
    image_width=240,
    validation_split=0.3,
    batch_size=32
)
'''------------------------------------------------'''
image_path = '/content/drive/MyDrive/IMG_0367.jpg'
data_dir = '/content/drive/MyDrive/image_dataset'#데이터 셋 경로
'''------------------------------------------------'''
data_preprocessor.get_ds(data_dir).normalize().shuffle()
train_ds = data_preprocessor.train_ds
valid_ds = data_preprocessor.valid_ds
test_ds = data_preprocessor.test_ds
'''------------------------------------------------'''
base_hidden_units = 16  # 은닉층의 유닛수
weight_decay = 1e-4    # L2 규제화 파라미터 Lambda
model=build_model(base_hidden_units, weight_decay)  # 모델 생성하기
'''------------------------------------------------'''
study(train_ds, valid_ds,model)
evaluate(model, test_ds)  # 모델 평가하기
'''------------------------------------------------'''
img_array = image_input(image_path)  # 사진 입력받기
image_output(model, img_array)  # 사진 결과 출력하기



