CREATE SCHEMA IF NOT EXISTS model_db DEFAULT CHARACTER SET UTF8;

CREATE TABLE IF NOT EXISTS model_db.dataset (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    label VARCHAR(20) NOT NULL,
    image_location VARCHAR(200) NOT NULL
);