# -*- coding: utf-8 -*-
"""output.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYk68a9uuuFQkzYtijEyr1wDSJY5rKwL
"""

import os
label=[]
def image_output(model,img_array,data_dir):
  for class_label in os.listdir(data_dir):
    label.append(class_label)
    # 3. 예측 수행
  predictions = model.predict(img_array)
  predicted_class = np.argmax(predictions[0])  # 가장 높은 확률을 갖는 클래스 인덱스
# 클래스 인덱스와 예측 결과 출력
  print("Predicted class:", label[predicted_class])